# Generated by Django 2.2.7 on 2019-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loldb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lol_id', models.CharField(max_length=100)),
                ('Rank', models.IntegerField(default=0)),
                ('Win', models.IntegerField(default=0)),
                ('Loss', models.IntegerField(default=0)),
            ],
        ),
    ]
