# Generated by Django 2.2.7 on 2020-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loldb',
            old_name='Loss',
            new_name='solo_loss',
        ),
        migrations.RenameField(
            model_name='loldb',
            old_name='Rank',
            new_name='solo_point',
        ),
        migrations.RenameField(
            model_name='loldb',
            old_name='Win',
            new_name='solo_win',
        ),
        migrations.RemoveField(
            model_name='loldb',
            name='lol_id',
        ),
        migrations.AddField(
            model_name='loldb',
            name='solo_rank',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='loldb',
            name='solo_tier',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='loldb',
            name='team_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loldb',
            name='team_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loldb',
            name='team_rank',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='loldb',
            name='team_tier',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='loldb',
            name='team_win',
            field=models.IntegerField(default=0),
        ),
    ]
